### ISSUE TITLE
bad image support

### ISSUE THREAD

**Issue by Augists** [mattn/docx2md#5]
Hello
in my use I found that `docx2md` seems to have some problems for images. I am not sure if it happens only on my computer.
Description of the situation: The picture only shows the top area, the rest is blank

**Comment by mattn** [comment]
If possible, could you please show me two pictures before and after?

**Comment by Augists** [comment]
![](https://s3.bmp.ovh/imgs/2022/02/ecab329f07282204.png)
left: original

**Comment by mattn** [comment]
I suspect that the base64 encoded image string needs to be escaped.
